---
deployment:
  tasks:
    - echo "Starting to Deploy"
    - export DEPLOYPATH=/home/techjayy/chess.techgebagency.website/wp-content/themes/chess-store
    - /bin/cp * $DEPLOYPATH
    - echo "Successfully Deployed"
